;this file for FamiTone2 library generated by text2data tool

framebyframe_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $70 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$02,$c0,$00,$02
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c9,$ce,$ce,$ca,$c5,$c2,$c0,$00,$06


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$25,$29,$2f,$33,$25,$29,$2f,$33,$25,$25,$2f,$33,$25,$25,$2f
	.byte $32,$81
@ref1:
	.byte $25,$29,$2f,$33,$25,$29,$2f,$33,$25,$29,$2f,$33,$25,$29,$2f,$32
	.byte $81
@ref2:
	.byte $25,$29,$2f,$33,$25,$29,$2f,$33,$25,$25,$2f,$33,$25,$25,$2f,$32
	.byte $81
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$11
	.word @ref1
@ref6:
	.byte $33,$2f,$29,$25,$33,$2f,$29,$25,$33,$29,$29,$25,$33,$33,$2f,$28
	.byte $81
@ref7:
	.byte $25,$33,$2f,$29,$25,$33,$29,$29,$33,$2f,$29,$25,$33,$2f,$29,$24
	.byte $81
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref7
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref7
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref7
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref14:
	.byte $a1,$00,$9b
@ref15:
	.byte $bf
@ref16:
	.byte $a1,$00,$9b
@ref17:
	.byte $bf
@ref18:
	.byte $86,$39,$39,$3f,$3f,$43,$35,$38,$85,$39,$3f,$3f,$39,$3f,$43,$38
	.byte $85
@ref19:
	.byte $39,$39,$3f,$3f,$43,$35,$38,$85,$39,$3f,$3f,$39,$3f,$43,$38,$85
	.byte $ff,$10
	.word @ref19
	.byte $ff,$10
	.word @ref19
@ref22:
	.byte $3c,$85,$44,$85,$47,$45,$46,$85,$4b,$41,$45,$47,$4b,$45,$46,$85
@ref23:
	.byte $3c,$85,$44,$85,$47,$45,$46,$85,$4b,$41,$45,$47,$4b,$45,$47,$40
	.byte $81
@ref24:
	.byte $4b,$47,$45,$41,$4b,$47,$45,$41,$3d,$41,$45,$41,$47,$45,$41,$40
	.byte $81
@ref25:
	.byte $9f,$3c,$9d
@ref26:
	.byte $a1,$00,$9b
@ref27:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref28:
	.byte $82,$3c,$85,$3c,$85,$46,$85,$4a,$85,$3c,$85,$3c,$85,$46,$85,$4a
	.byte $85
@ref29:
	.byte $3c,$85,$3c,$85,$46,$85,$4a,$85,$3c,$85,$3c,$85,$46,$85,$4a,$85
	.byte $ff,$10
	.word @ref29
	.byte $ff,$10
	.word @ref29
	.byte $ff,$10
	.word @ref29
	.byte $ff,$10
	.word @ref29
@ref34:
	.byte $4a,$85,$4a,$85,$46,$85,$3c,$85,$4a,$85,$4a,$85,$46,$85,$3c,$85
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
@ref40:
	.byte $4a,$85,$4a,$85,$46,$85,$3c,$85,$86,$3a,$85,$32,$85,$32,$85,$00
	.byte $85
@ref41:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref42:
	.byte $bf
@ref43:
	.byte $bf
@ref44:
	.byte $84,$0c,$99,$09,$0c,$99,$12,$81
@ref45:
	.byte $0c,$99,$0d,$10,$99,$10,$81
@ref46:
	.byte $0c,$99,$09,$0c,$99,$12,$81
	.byte $ff,$07
	.word @ref45
	.byte $ff,$07
	.word @ref46
	.byte $ff,$07
	.word @ref45
	.byte $ff,$07
	.word @ref46
	.byte $ff,$07
	.word @ref45
	.byte $ff,$07
	.word @ref46
	.byte $ff,$07
	.word @ref45
@ref54:
	.byte $bf
@ref55:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
@ref60:
	.byte $bf
@ref61:
	.byte $bf
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
