;this file for FamiTone2 library generated by text2data tool

framebyframe_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,331,276
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $70 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$02,$c0,$00,$02
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c9,$ce,$ce,$ca,$c5,$c2,$c0,$00,$06
@env4:
	.byte $cf,$cf,$ce,$cc,$c8,$c0,$00,$05


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$25,$29,$2f,$33,$25,$29,$2f,$33,$25,$25,$2f,$33,$25,$25,$2f
	.byte $32,$81
@ref1:
	.byte $25,$29,$2f,$33,$25,$29,$2f,$33,$25,$29,$2f,$33,$25,$29,$2f,$32
	.byte $81
@ref2:
	.byte $25,$29,$2f,$33,$25,$29,$2f,$33,$25,$25,$2f,$33,$25,$25,$2f,$32
	.byte $81
	.byte $ff,$11
	.word @ref1
	.byte $ff,$11
	.word @ref2
	.byte $ff,$11
	.word @ref1
@ref6:
	.byte $33,$2f,$29,$25,$33,$2f,$29,$25,$33,$29,$29,$25,$33,$33,$2f,$28
	.byte $81
@ref7:
	.byte $25,$33,$2f,$29,$25,$33,$29,$29,$33,$2f,$29,$25,$33,$2f,$29,$24
	.byte $81
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref7
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref7
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref7
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref14:
	.byte $a1,$00,$9b
@ref15:
	.byte $bf
@ref16:
	.byte $a1,$00,$9b
@ref17:
	.byte $bf
@ref18:
	.byte $86,$33,$33,$39,$3d,$39,$33,$38,$85,$33,$39,$33,$39,$41,$39,$32
	.byte $85
@ref19:
	.byte $33,$39,$33,$39,$3d,$39,$3c,$85,$39,$41,$43,$41,$43,$47,$4a,$85
@ref20:
	.byte $33,$33,$39,$3d,$39,$33,$38,$85,$33,$39,$33,$39,$41,$39,$32,$85
	.byte $ff,$10
	.word @ref19
@ref22:
	.byte $3c,$85,$44,$85,$47,$45,$46,$85,$4b,$41,$45,$47,$4b,$45,$46,$85
@ref23:
	.byte $3c,$85,$44,$85,$47,$45,$46,$85,$4b,$41,$45,$47,$4b,$45,$47,$40
	.byte $81
@ref24:
	.byte $4b,$47,$45,$41,$4b,$47,$45,$41,$3d,$41,$45,$41,$47,$45,$41,$40
	.byte $81
@ref25:
	.byte $9f,$3c,$9d
@ref26:
	.byte $a1,$00,$9b
@ref27:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref28:
	.byte $82,$3c,$85,$3c,$85,$46,$85,$4a,$85,$3c,$85,$3c,$85,$46,$85,$4a
	.byte $85
@ref29:
	.byte $3c,$85,$3c,$85,$46,$85,$4a,$85,$3c,$85,$3c,$85,$46,$85,$4a,$85
	.byte $ff,$10
	.word @ref29
	.byte $ff,$10
	.word @ref29
	.byte $ff,$10
	.word @ref29
	.byte $ff,$10
	.word @ref29
@ref34:
	.byte $4a,$85,$4a,$85,$46,$85,$3c,$85,$4a,$85,$4a,$85,$46,$85,$3c,$85
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref34
@ref40:
	.byte $4a,$85,$4a,$85,$46,$85,$3c,$85,$86,$3a,$85,$32,$85,$32,$85,$00
	.byte $85
@ref41:
	.byte $bf
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref42:
	.byte $bf
@ref43:
	.byte $bf
@ref44:
	.byte $84,$0c,$99,$09,$0c,$99,$12,$81
@ref45:
	.byte $0c,$99,$0d,$10,$99,$10,$81
@ref46:
	.byte $0c,$99,$09,$0c,$99,$12,$81
	.byte $ff,$07
	.word @ref45
	.byte $ff,$07
	.word @ref46
	.byte $ff,$07
	.word @ref45
	.byte $ff,$07
	.word @ref46
	.byte $ff,$07
	.word @ref45
	.byte $ff,$07
	.word @ref46
	.byte $ff,$07
	.word @ref45
@ref54:
	.byte $bf
@ref55:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
@ref60:
	.byte $bf
@ref61:
	.byte $bf
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref70:
	.byte $88,$09,$05,$0f,$09,$05,$05,$08,$85,$09,$05,$0f,$09,$05,$05,$02
	.byte $85
@ref71:
	.byte $09,$05,$0f,$09,$05,$05,$08,$85,$09,$05,$0f,$09,$05,$05,$02,$85
	.byte $ff,$10
	.word @ref71
	.byte $ff,$10
	.word @ref71
@ref74:
	.byte $09,$05,$0f,$09,$05,$05,$08,$85,$09,$09,$0f,$0f,$05,$05,$02,$85
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref71
	.byte $ff,$10
	.word @ref71
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref74
	.byte $ff,$10
	.word @ref71
	.byte $ff,$10
	.word @ref71
	.byte $ff,$10
	.word @ref71
@ref87:
	.byte $09,$05,$05,$0f,$13,$17,$16,$85,$09,$09,$05,$09,$05,$09,$0e,$85
	.byte $ff,$10
	.word @ref87
@ref89:
	.byte $09,$05,$05,$0f,$13,$17,$17,$0f,$09,$05,$0f,$09,$05,$05,$02,$85
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
@ref100:
	.byte $bf
@ref101:
	.byte $bf
@ref102:
	.byte $bf
@ref103:
	.byte $bf
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@ref108:
	.byte $bf
@ref109:
	.byte $bf
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref110:
	.byte $00,$bd
@ref111:
	.byte $00,$bd
@ref112:
	.byte $00,$bd
@ref113:
	.byte $00,$bd
@ref114:
	.byte $82,$36,$8d,$3a,$8d,$40,$85,$44,$8d,$32,$85
@ref115:
	.byte $36,$8d,$3a,$8d,$40,$85,$44,$8d,$32,$85
@ref116:
	.byte $36,$8d,$3a,$8d,$40,$8d,$36,$8d
	.byte $ff,$08
	.word @ref116
	.byte $ff,$0a
	.word @ref115
	.byte $ff,$0a
	.word @ref115
	.byte $ff,$08
	.word @ref116
	.byte $ff,$08
	.word @ref116
	.byte $ff,$0a
	.word @ref115
	.byte $ff,$0a
	.word @ref115
@ref124:
	.byte $3a,$85,$3c,$85,$40,$85,$36,$8d,$32,$85,$36,$85,$32,$85
@ref125:
	.byte $00,$bd
@ref126:
	.byte $00,$bd
@ref127:
	.byte $00,$bd
@ref128:
	.byte $00,$bd
@ref129:
	.byte $00,$bd
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref130:
	.byte $bf
@ref131:
	.byte $bf
@ref132:
	.byte $88,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a
	.byte $85
@ref133:
	.byte $1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85
	.byte $ff,$10
	.word @ref133
@ref135:
	.byte $1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1b,$1b,$1b,$1b,$1b,$1a
	.byte $81
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $ff,$11
	.word @ref135
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $ff,$11
	.word @ref135
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $ff,$11
	.word @ref135
	.byte $ff,$10
	.word @ref133
	.byte $ff,$10
	.word @ref133
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref150:
	.byte $bf
@ref151:
	.byte $bf
@ref152:
	.byte $bf
@ref153:
	.byte $bf
@ref154:
	.byte $bf
@ref155:
	.byte $bf
@ref156:
	.byte $bf
@ref157:
	.byte $bf
@ref158:
	.byte $bf
@ref159:
	.byte $bf
@ref160:
	.byte $bf
@ref161:
	.byte $bf
@ref162:
	.byte $bf
@ref163:
	.byte $bf
@ref164:
	.byte $bf
@ref165:
	.byte $bf
@ref166:
	.byte $bf
@ref167:
	.byte $bf
@ref168:
	.byte $bf
@ref169:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref170:
	.byte $f9,$85
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref171:
	.byte $f9,$85
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref172:
	.byte $f9,$85
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref173:
	.byte $f9,$85
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref174:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$04
@song3ch0loop:
@ref175:
	.byte $82,$32,$85,$36,$85,$3b,$3c,$85,$40,$85,$44,$85,$49,$4a,$85,$00
	.byte $85
@ref176:
	.byte $4a,$85,$48,$85,$45,$40,$85,$3c,$85,$3a,$85,$37,$32,$85,$00,$85
@ref177:
	.byte $32,$85,$36,$85,$3b,$3c,$85,$40,$85,$44,$85,$49,$4a,$85,$00,$85
	.byte $ff,$10
	.word @ref176
@ref179:
	.byte $32,$85,$36,$85,$3b,$3c,$85,$01,$32,$85,$36,$85,$3b,$3c,$85,$00
	.byte $81
	.byte $ff,$10
	.word @ref177
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref181:
	.byte $bf
@ref182:
	.byte $bf
@ref183:
	.byte $bf
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref187:
	.byte $82,$32,$99,$36,$85,$3a,$85,$3d,$40,$8d
@ref188:
	.byte $32,$99,$36,$85,$3a,$85,$3d,$40,$8d
@ref189:
	.byte $4a,$99,$48,$85,$44,$85,$3d,$3a,$8d
	.byte $ff,$09
	.word @ref188
@ref191:
	.byte $32,$8d,$4a,$8d,$32,$8d,$4a,$8d
@ref192:
	.byte $32,$8d,$3a,$8d,$40,$8d,$4a,$8d
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref193:
	.byte $88,$12,$85,$08,$85,$12,$85,$12,$85,$08,$85,$12,$85,$08,$85,$12
	.byte $85
@ref194:
	.byte $12,$85,$08,$85,$12,$85,$12,$85,$08,$85,$12,$85,$08,$85,$12,$85
@ref195:
	.byte $09,$09,$09,$09,$13,$13,$13,$13,$09,$09,$09,$09,$13,$13,$13,$12
	.byte $81
	.byte $ff,$11
	.word @ref195
	.byte $ff,$11
	.word @ref195
	.byte $ff,$10
	.word @ref194
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref199:
	.byte $bf
@ref200:
	.byte $bf
@ref201:
	.byte $bf
@ref202:
	.byte $bf
@ref203:
	.byte $bf
@ref204:
	.byte $bf
	.byte $fd
	.word @song3ch4loop
