;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $80,$ff,$81,$df,$82,$01,$89,$32,$8a,$06,$01,$80,$f3,$01,$80,$bb
	.byte $01,$80,$f9,$01,$80,$ff,$81,$3f,$89,$31,$01,$80,$f3,$01,$80,$bb
	.byte $01,$80,$f9,$01,$80,$73,$89,$30,$01,$00
